language: python
os:
  - linux
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

services:
  - docker

script:
  - pytest